version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: event-reward-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-reward-network

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/gateway
      - JWT_SECRET=your_jwt_secret_should_be_long_and_random
      - AUTH_SERVICE_URL=http://auth-server:3001
      - EVENT_SERVICE_URL=http://event-server:3002
    networks:
      - event-reward-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=your_jwt_secret_should_be_long_and_random
      - JWT_EXPIRATION=1h
    networks:
      - event-reward-network

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/event
      - JWT_SECRET=your_jwt_secret_should_be_long_and_random
    networks:
      - event-reward-network

networks:
  event-reward-network:
    driver: bridge

volumes:
  mongodb_data:
